### ISSUE TITLE
Weitere Output-KBS neben EPSG:25832

### ISSUE THREAD

**Issue by BiggiPacco** [kreis-viersen/umringpolygon-zu-xplanung#19]
Moin,
ich habe gerade meine 1. xplan.gml mit diesem Script ertellt. So weit, so gut. Ein negativer Punkt fällt mir allerdings auf: In Deutschland ist im östlichen Bereich der EPSG-Code 25833 üblich. 
Der Layer, aus dem die xplan.gml erstellt wurde, hat EPSG-Code 25833. Die xplan.gml dann aber 25832. Der Code wird also nicht übernommen.
Wäre super, wenn das abgeändert wird. Ideal wäre wohl eine weitere Option beim Erstellen der Datei. Alternativ Übernahme des EPSG-Codes vom Ursprungslayer.

**Comment by pathmapper** [comment]
Moin @BiggiPacco,

vielen Dank für's Feedback und schön zu hören, dass das Script auch woanders genutzt wird.

Wir schauen uns das gerne 'mal an, hier schon einmal das angepasste Skript, welches dann `EPSG:25833` für die XPlanGML verwendet (unabhängig vom Input-KBS):






 

[xplan-umring-25833.zip](https://github.com/kreis-viersen/umringpolygon-zu-xplanung/files/11097401/xplan-umring-25833.zip)

**Comment by BiggiPacco** [comment]
Moin @pathmapper,

perfekt. Getestet und funktioniert. Dankeschön für die superschnelle Antwort :)

**Comment by pathmapper** [comment]
Moin @BiggiPacco,

mit Version 2.0.0 steht das Tool jetzt als Plugin über das QGIS-Plugin-Repository zur Verfügung
https://plugins.qgis.org/plugins/xplan-umring/

und es können diverse EPSG-Codes als KBS ausgewählt werden:
![grafik](https://github.com/kreis-viersen/xplan-umring/assets/20856381/006195dc-616e-4525-b36b-1d97d9c5398d)
![grafik](https://github.com/kreis-viersen/xplan-umring/assets/20856381/b7d8dab0-8f9c-434e-808a-9cfae07c3b9d)

Noch einmal danke für die Anregung!
