### ISSUE TITLE
Kann Modell nicht ausführen. - CRITICAL - native:retainfields_1, Änderung des Models

### ISSUE THREAD

**Issue by petershr01** [kreis-viersen/umringpolygon-zu-xplanung#4]
QGIS-Version [3.16.6]
W10

Hallo, bei einem ersten Test mit Ihrem Model kamen diese Fehlermeldungen. In der Modellentwurf-Ansicht ist der Punkt 'alle Felder löschen' rot Dargestellt. Habe dann diesen Eintrag neu erstellt, mit dem Algorithmus "Feld(er) löschen", damit hat es dann  funktioniert. Ich könnte ggf. die geänderte Datei zusenden.

Fehlermeldungen:
**Fehlermeldung im Modeler:**
Kann Modell nicht ausführen. Die folgenden Algorithmen stehen auf diesem System nicht zur Verfügung: native:retainfields_1
Ausführung nach 0.10 Sekunden gescheitert

**Python-Fehler:**
2021-06-11T10:20:40     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 161, in editComponent
              self.edit()
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 135, in edit
              self.component().configuration())
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins\processing\modeler\ModelerParametersDialog.py", line 77, in __init__
              self.setWindowTitle(self._alg.displayName())
             AttributeError: 'NoneType' object has no attribute 'displayName'

**Fehlermeldung Verarbeitung:**
2021-06-11T10:24:57     CRITICAL    Kann Modell nicht ausführen. Die folgenden Algorithmen stehen auf diesem System nicht zur Verfügung: native:retainfields_1

**Comment by pathmapper** [comment]
Hallo, danke für die Rückmeldung! 

Der Algorithmus "retainfields/"Zu erhaltene Felder" ist relativ neu und in QGIS LTR noch nicht enthalten.
Wir verwenden hier QGIS LR (aktuell 3.18) und da tritt das Problem nicht auf, weil der Algorithmus dort verfügbar ist.
Wenn es allerdings außer uns noch Nutzer gibt, die QGIS LTR einsetzten, macht es natürlich Sinn, dass das Modell auch dort funktioniert.

Der Algorithums hat aktuell den Zweck, alle eventuell vorhanden Felder zu löschen, bevor das Modell ensprechend der Benutzereingabe selber welche anlegt. 
Vielleicht ist der Algorithmus gar nicht nötig, ich muss mal schauen, was passiert, wenn es ein Feld, welches das Modell anlegen möchte, schon gibt.

Ja, gerne das Modell zusenden (per Email an open@kreis-viersen.de oder als Zip-Datei hier an einen Kommentar anhängen). Würde mich interessieren, wie das mit "Feld(er) löschen" umgesetzt ist.

**Comment by pathmapper** [comment]
Hinweis im Readme: https://github.com/kreis-viersen/umringpolygon-zu-xplanung#readme


![grafik](https://user-images.githubusercontent.com/20856381/121673285-03667300-cab1-11eb-8ff5-322ba4654445.png)

**Comment by pathmapper** [comment]
Mit Version [v0.3.0](https://github.com/kreis-viersen/umringpolygon-zu-xplanung/releases/tag/v0.3.0) wird jetzt der Algorithums "Feld(er) löschen" anstatt "Zu erhaltende Felder" verwendet, damit das [Modell ](https://github.com/kreis-viersen/umringpolygon-zu-xplanung/releases/download/v0.3.0/umringpolygon-zu-xplanung_v0_3_0.zip) auch mit dem aktuellen QGIS LTR funktioniert.

@petershr01, noch einmal Danke für den Hinweis 👍

**Comment by petershr01** [comment]
Hallo,

 

wollte gerade die Datei senden, aber das scheint wohl nicht mehr nötig zu sein. Kann ich in diesem Zusammenhang mal eine allgemeine Frage zum

Thema XPlanung stellen? Wie ist der Stand zur Umsetzung bei Ihnen, nutzen Sie nur QGIS für diese zwecke. 

Hintergrung, bin seit gut 4 Monaten bei der Stadt Magdeburg, Stadtplanungsamt. Hier bei der Stadt, aber auch im Land generell ist dieses Thema derzeit

nicht sehr presänt. Ich bin eigentlich nur für den FNP 'zuständig', aber die rechtsverbindlich Planung sitzt ja neben an, und da ist das Thema ja noch dringender.

Im Moment erstelle ich gerade ein Testprojekt mit QGIS, XPlanung Plugin, PostgreSQL-DB und der XPlanungs-Fachschale für PostGIS.

Das größte Problem ist aber der Export, habe auch schon etliche Versuche mit dem Tool 'GML Toolbox-Freeware' durchgeführt. Diese waren dann einigermaßen erfolgreich,

aber nur in einem sehr kleinen Beispiel. Zumindest ist ihr Model ein sehr guter ansatz um bei den B-Plänen mal anzufangen.    

 
Beste Grüße nach Viersen

Gesendet: Montag, 14. Juni 2021 um 07:13 Uhr
Von: "pathmapper" ***@***.***>
An: "kreis-viersen/umringpolygon-zu-xplanung" ***@***.***>
Cc: "Peter" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [kreis-viersen/umringpolygon-zu-xplanung] Kann Modell nicht ausführen. - CRITICAL - native:retainfields_1, Änderung des Models (#4)


 

Mit Version v0.3.0 wird jetzt der Algorithums "Feld(er) löschen" anstatt "Zu erhaltende Felder" verwendet, damit das Modell  auch mit dem aktuellen QGIS LTR funktioniert.

@petershr01, noch einmal Danke für den Hinweis 👍

**Comment by pathmapper** [comment]
Für uns selbst sind derzeit nur die B-Plan Umringe von Interesse, und ja, wir nutzen ausschließlich QGIS mit dem Modell und Browsertool hierfür.

Den Workflow mit Postgres/PostGIS und XPlanung Plugin für QGIS hatte ich mir auch kurz angeschaut, ebenso die GML-Toolbox für den Export.

 Aber das ist doch recht überdimensioniert für unseren aktuellen UseCase, deshalb der hier gewählte Ansatz mit QGIS Modell, standard QGIS GML Export und Browserkonverter für XPlanGML.

@tschuettenberg von der QGIS Anwendergruppe Deutschland hat hier einiges zum Thema XPlanung und QGIS zusammengetragen: https://www.qgis.de/doku.php/site/xplanung/start

Es gab in der Vergangenheit auch Anwendertreffen hierzu https://www.qgis.de/doku.php/site/anwendertreffen/themenstammtische/qgis_xplanung, und es könnte eventuell bald auch wieder eines stattfinden.

Bei Interesse am Besten mal bei https://www.qgis.de/ / @tschuettenberg melden.
